version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - run:
         name: test
         shell: /bin/bash -o pipefail
         command: |
                  set +e
                  true || error=true
                  sleep 5
                  true || error=true
                  sleep 5
                  false || error=true
                  sleep 5
                  true || error=true
                  echo "this happened" >> /tmp/happened
                  sleep 5
                  if [[ $error ]]
                  then
                      exit -1
                  fi
      - run: 
         name: test2
         command: |
                  cat /tmp/happened
