version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - run:
         name: test
         shell: /bin/bash -o pipefail
         command: |
                  true
                  true
                  false
                  true
