version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: brringtestuser
          POSTGRES_DB: brringtest
          POSTGRES_PASSWORD: brringtestpassword
        command: [--max_connections 500]
    steps:
      - run:
         name: test
         command:  echo 'export TERM=xterm-256color' >> $BASH_ENV
      - run: echo $TERM                     
                  
