version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - run:
         name: test
         shell: /bin/bash -eo pipefail
         command: |
                  true
                  sleep 1000
                  true
                  sleep 1000
                  false
                  sleep 2000
                  true
                  sleep 1000
                  true
