version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest

    steps:
      - run:
         name: test
         command:  echo 'export TERM=xterm-256color' >> $BASH_ENV
      - run: echo $TERM                     
                  
