version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk-stretch

    
    steps:
      - run:
         name: test
         shell: /bin/bash -o pipefail
         command: |
                  false
                  true
                  true
