version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - run:
         name: test
         shell: /bin/bash -o pipefail
         command: |
                  set +e
                  true
                  sleep 5
                  true
                  sleep 5
                  false
                  sleep 5
                  true
                  echo "this happened" >> /tmp/happened
                  sleep 5
                  true
      - run: 
         name: test2
         command: |
                  cat /tmp/happened
